name: build-xs-melodic

on:
  push:
    branches:
      - main
      - devel
  pull_request:
    branches:
      - main
      - devel

defaults:
  run:
    shell: bash

jobs:
  industrial_ci:
    strategy:
      matrix:
        env:
          - {ROS_DISTRO: melodic, ROS_REPO: main}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Create src directory for xs
        run: |
          rm interbotix_ros_xseries/CATKIN_IGNORE
          mkdir src
          mv interbotix_ros_xseries src
      - uses: 'ros-industrial/industrial_ci@master'
        env: ${{matrix.env}}
